name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - page-source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_DASHBOARD_ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: build
        BUILD_SCRIPT: yarn && yarn build